# Runs pre-commit on every push or pull request.

name: pre-commit
on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install pre-commit
      - run: pre-commit run --all-files
