name: Publish Python package to pypi

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    environment: release
    permissions:
      id-token: write

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
          pipx install poetry
          pipx inject poetry poetry-dynamic-versioning

      - name: Build package
        run: poetry build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
